### ISSUE TITLE
https instead of http for chartmuseum.jenkins-x.io

### ISSUE THREAD

**Issue by rainmanh** [jenkins-x/jx#3828]
### Steps to reproduce the behaviour
jx install
### Expected behaviour

to install the dependencies

### Actual behavior

Jenkins fails to install the dependencies

### Jx version
jx                 2.0.71

The output of `jx version` is:

NAME               VERSION
jx                 2.0.71
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.14.1
helm client        Client: v2.13.1+g618447c
git                git version 2.17.2
Operating System   "Amazon Linux release 2 (Karoo)"

```
retrying after error:failed to run 'helm repo add jenkins-x http://chartmuseum.jenkins-x.io' command in directory '', output: 'Error: Looks like "http://chartmuseum.jenkins-x.io" is not a valid chart repository or cannot be reached: Failed to fetch http://chartmuseum.jenkins-x.io/index.yaml : 403 Forbidden'```

### Jenkins type

- [ ] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### Kubernetes cluster
EKS
### Operating system / Environment

Amazon Linux

------

Would be possible to have an option for https not only http for the Sources?

On my environment We are behind a Firewall and We are only allowed https connections to the outside which can be very limiting.

I have been reading through the parameters but I am not sure whether I can change that behaviour as the URL seems hard-coded

Many thanks

**Comment by rainmanh** [comment]
Anyone?
Maybe to have the chance of using a custom URL instead of the hardcoded one?
Makes any sense?

**Comment by rawlingsj** [comment]
we have a https URL which goes direct to the GCS bucket https://storage.googleapis.com/chartmuseum.jenkins-x.io - I think that should solve this issue but please reopen if not.

**Comment by rainmanh** [comment]
@rawlingsj , apologies.
I forgot to mention I am using 
```jx install``` over an existing EKS cluster and I noticed the `http://chartmuseum.jenkins-x.io` is hardcoded in the *jx* binary instead.

Anyway around running the `jx install` adding the `https://storage.googleapis.com/chartmuseum.jenkins-x.io` as the bucket source ?

**Comment by rawlingsj** [comment]
yeah good point - let's change `jx install` to use the https URL I'll send a PR shortly and that should catch all the places.

**Comment by rawlingsj** [comment]
ok that's releasing ATM, let's reopen if we find any other places that use the old http URL.

**Comment by InsOpDe** [comment]
still facing the same issue: 
```bash
> jx add app tekton
error: failed to run 'helm fetch tekton --untardir /tmp/jx-helm-fetch-tekton-479148320 --untar --repo https://storage.googleapis.com/chartmuseum.jenkins-x.
io' command in directory '', output: 'Error: failed to fetch https://storage.googleapis.com/charts/tekton-0.0.42.tgz : 403 Forbidden'
```
if these seem not to be related, im glad to open a new issue
